#!/bin/bash -e
cd $(dirname $0)
PATH=$HOME/gopath/bin:$GOPATH/bin:$PATH

if ! type -p goveralls; then
  echo go get github.com/mattn/goveralls
  go get github.com/mattn/goveralls
fi

D=$PWD

for d in `find parameter -type d` ics value .; do
    echo $d...
    cd $d
    go test -v -covermode=count -coverprofile=coverage.out .
    go tool cover -func=coverage.out
    [ -z "$COVERALLS_TOKEN" ] || goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
    cd $D
done
